#ifndef SYTELINE_TECHNIQUE_CODE_MSSQLSCANNER_H
#define SYTELINE_TECHNIQUE_CODE_MSSQLSCANNER_H

#ifndef SYTELINE_TECHNIQUE_SYSTEM_ECOTOPE_BASE_H
#include "Technique/Ecotope/Base.h"
#endif
#ifndef SYTELINE_TECHNIQUE_CODE_SQLDECLARATION_H
#include "Technique/Code/SqlDeclaration.h"
#endif
#ifndef SYTELINE_TECHNIQUE_CODE_SQLPROCEDURE_H
#include "Technique/Code/SqlProcedure.h"
#endif
#ifndef SYTELINE_TECHNIQUE_CODE_SQLVARIABLE_H
#include "Technique/Code/SqlVariable.h"
#endif
#ifndef SYTELINE_TECHNIQUE_CODE_SQLARGUMENT_H
#include "Technique/Code/SqlArgument.h"
#endif

using namespace SyteLine::Technique::Code;

#ifndef YY_DECL

#define	YY_DECL \
    int SyteLine::Technique::Code::CMssqlScanner::Flex(CMssqlDriver& oDriver)
#endif

#ifndef __FLEX_LEXER_H
#define yyFlexLexer CMssqlScannerFlexLexer
#include "FlexLexer.h"
#undef yyFlexLexer
#endif

namespace SyteLine { namespace Technique { namespace Code 
{
    class CMssqlDriver;

    class SYTELINE_LIBRARY_EXPORT CMssqlScanner : public CMssqlScannerFlexLexer
    {
    public:
        enum EMatched
        {
            E_MATCHED_NONE = 0,
            E_MATCHED_DECLARATION,
            E_MATCHED_PARAMETER_NAME,
            E_MATCHED_PARAMETER_TYPE,
            E_MATCHED_PARAMETER_VALUE,

            E_MATCHED_PROCEDURE,
            E_MATCHED_ARGUMENT_SWAP,
            E_MATCHED_ARGUMENT_VALUE
        };

        enum EStage
        {
            E_STAGE_BODY,
            E_STAGE_PRCEDURE_DECLARATION,
            E_STAGE_FUNCTION_DECLARATION,
            E_STAGE_PROCEDURE,
            E_STAGE_DECLARE
            
        };

    protected:
        EStage m_eStage;
        EMatched m_eMatched;
        vector<mstring> m_stlLeftBraces;

        CSqlDeclaration m_oDeclaration;
        CSqlProcedure m_oProcedure;
        CSqlVariable m_oVariable;
        CSqlArgument m_oArgument;

    public:
        /** Create a new scanner object. The streams arg_yyin and arg_yyout default
        * to cin and cout, but that assignment is only made when initializing in
        * yylex(). */
        CMssqlScanner(istream* pYYIn = 0, ostream* pYYOut = 0);

        /** Required for virtual functions */
        virtual ~CMssqlScanner();

        /** This is the main lexing function. It is generated by flex according to
        * the macro declaration YY_DECL above. The generated bison parser then
        * calls this virtual function to fetch new tokens. */
        virtual int Flex(CMssqlDriver& oDriver);

    public:
        bool InDeclaration();
    };
}}}

#endif
